### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by TerableCoder** [teralove/iod-vanguard#1]
It correctly says if I get the basilisk vanguard, but doesn't automatically get me the basilisk quest when I unequip my chest.
![tera_screenshot_20181128_014438](https://user-images.githubusercontent.com/31596711/49133840-8509a300-f2af-11e8-8d6a-b3e5f10505f5.png)
[01:40:55 GMT-0500] ERROR tera-proxy-game: [dispatch] write: failed to generate C_AVAILABLE_EVENT_MATCHING_LIST<1>
error: [protocol] write ("C_AVAILABLE_EVENT_MATCHING_LIST"): invalid code "null"'
    at TeraProtocol.write (C:\Users\X\tera-proxy\node_modules\tera-data-parser\lib\protocol\index.js:469:15)
    at Dispatch.write (C:\Users\X\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:427:26)
    at Module.send (C:\Users\X\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\module.js:85:30)
    at Timeout.setTimeout [as _onTimeout] (C:\Users\X\tera-proxy\bin\node_modules\iod-vanguard-master\index.js:36:21)

**Comment by TerableCoder** [comment]
When I start proxy:

[01:50:19 GMT-0500] ERROR tera-proxy-game: [dispatch] hook: unrecognized hook target C_EQUIP_ITEM<2>
    at new IodVanguard (C:\Users\X\tera-proxy\bin\node_modules\iod-vanguard-master\index.js:21:9)
    at Dispatch.load (C:\Users\X\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:210:25)
    at Dispatch.connection.dispatch.on (C:\Users\X\tera-proxy\bin\lib\proxy.js:240:29)
    at Dispatch.emit (events.js:182:13)
[01:50:19 GMT-0500] ERROR tera-proxy-game: [dispatch] hook: unrecognized hook target C_UNEQUIP_ITEM<1>
    at new IodVanguard (C:\Users\X\tera-proxy\bin\node_modules\iod-vanguard-master\index.js:26:9)
    at Dispatch.load (C:\Users\X\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:210:25)
    at Dispatch.connection.dispatch.on (C:\Users\X\tera-proxy\bin\lib\proxy.js:240:29)
    at Dispatch.emit (events.js:182:13)
[01:50:19 GMT-0500] ERROR tera-proxy-game: [dispatch] hook: unrecognized hook target C_AVAILABLE_EVENT_MATCHING_LIST<1>
    at new IodVanguard (C:\Users\X\tera-proxy\bin\node_modules\iod-vanguard-master\index.js:41:9)
    at Dispatch.load (C:\Users\X\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:210:25)
    at Dispatch.connection.dispatch.on (C:\Users\X\tera-proxy\bin\lib\proxy.js:240:29)
    at Dispatch.emit (events.js:182:13)

**Comment by ghost** [comment]
Its working fine for me. I guess you are missing some opcode and or an missing definition.
C_AVAILABLE_EVENT_MATCHING_LIST this one should be missing cause its not mapped automatically on EU dont know if Na is the same.

**Comment by teralove** [comment]
Your proxy needs the opcodes. I only have NA opcodes on hand.

protocol.339840.map

C_EQUIP_ITEM = 33005
C_UNEQUIP_ITEM = 27933
C_AVAILABLE_EVENT_MATCHING_LIST = 31582

**Comment by ghost** [comment]
Here are the EU ones if you need them.

protocol.339841.map

C_EQUIP_ITEM = 45331
C_UNEQUIP_ITEM = 50915
C_AVAILABLE_EVENT_MATCHING_LIST = 29693

**Comment by TerableCoder** [comment]
Where do I add these numbers(NA)?

**Comment by TerableCoder** [comment]
protocol.339840.map is where?

**Comment by ghost** [comment]
Go into your tera proxy root folder then /node_modules/tera-data/map. 
Open the protocol.339840.map file and put the needed opcodes in there.

**Comment by ghost** [comment]
Btw to make things simple the search function in the folder will work too.

**Comment by TerableCoder** [comment]
ty!
